export const OUR_STORY_POEM = [
  'This is the story of how we came to be,',
  'The wonderful story of Sunny and Kimmy,',
  'A boy from a small town in India,',
  'Who came to a country much wetter and windier,',
  'And a girl from the county of Merseyside,',
  'Ultimately teamed up and embarked on a whirlwind ride,',
  'In a company called Flex is where we first met,',
  'A part of our journey that we could never forget,',
  'Starting off as teammates we soon became friends,',
  "It became clear quote early on that our journey wouldn't end,",
  'As we got to know each other we figured out the score,',
  'We soon evolved into something much more,',
  'August 2013 is when we went on our first date,',
  'We walked around Chester Zoo and watched the animals as they ate,',
  'We had an amazing time and such a laugh,',
  "And we knew right then that we'd embarked on a wonderful path,",
  'In October of that year, a few dates later,',
  'We decided to make it official and our relationship got much greater,',
  'From then on, we grew and our bond continued to get stronger,',
  "And we couldn't bear to be living apart for much longer,",
  'In April 2016, we bought our first home,',
  "Since then, we'd never spent another day alone,",
  'We soon adopted our little furry baby,',
  'None other than the one and only Dixie,',
  "Through the years we've had so many highs,",
  "But if we told you it's always been smooth sailing, we'd be telling you lies,",
  'But through all the highs and lows, our love for each other has never diminished,',
  "It's cemented us together and ensured we're never finished,",
  'Shortly after our 12th anniversary is the perfect time to flick the switch,',
  "After over a decade of beautiful memories later, we've decided to get hitched,",
  "We're truly excited to invite you to a day/night full of joy and laughter,",
  "We'd love for you to help us celebrate our 'Happily ever after'!",
];
